services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
    ports:
      - '3306:3306'
    networks:
      - app-network

  app:
    image: flow
    container_name: blocked-file-extension
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - 'DB_HOST=mysql'
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    depends_on:
      - mysql
    ports:
      - '8080:8080'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge