spring:
  mvc:
    hidden-method:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: ${APPLICATION_DATASOURCE_URL}
    username: ${APPLICATION_DATASOURCE_USERNAME}
    password: ${APPLICATION_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
