name: flow-ci-cd.yml

on:
  push:
    branches:
      - main
      - feat/prod_setting-#21

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Copy Secrets
        uses: microsoft/variable-substitution@v1
        with:
          files: './src/main/resources/application-prod.yml'
        env:
          spring.datasource.url: ${{ secrets.APPLICATION_DATASOURCE_URL }}
          spring.datasource.username: ${{ secrets.APPLICATION_DATASOURCE_USERNAME }}
          spring.datasource.password: ${{ secrets.APPLICATION_DATASOURCE_PASSWORD }}

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build -Dspring.profiles.active=prod

      - name: Prepare File for Deployment
        run: |
          mkdir -p deployment/app/build/libs
          cp dockerfile docker-compose-prod.yml .env deployment/
          cp -r ./build/libs deployment/app/build

      - name: Get Github Actions IP
        id: ip
        uses: candidob/get-runner-ip@v1.0.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Add Github Actions IP on Security Group
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Upload files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "deployment/*"
          target: "/home/ec2-user/"

      - name: Deploy using Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/deployment/
            docker-compose -f docker-compose-prod.yml down
            docker system prune -f
            docker-compose -f docker-compose-prod.yml up -d --build

      - name: Remove Github Actions IP from Security Group
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
